### ISSUE TITLE
adsmsg/__init__ needs all the probufs

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/ADSPipelineMsg#27]
nonbib and metrics are missing.

**Comment by spacemansteve** [comment]
the follow tests are currently failing and I do not plan to fix them now:
% python adsmsg/tests/test_denormalized_record.py 
F..
======================================================================
FAIL: test_full_record (__main__.TestDenormalizedRecord)
This is here also as a documentation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adsmsg/tests/test_denormalized_record.py", line 111, in test_full_record
    self.assertEqual(expected, r.toJSON())
AssertionError: {'body': u'body body', 'read_count': 10, 'doctype_facet_hier': [u'0/Article', u' [truncated]... != {'keywordSchema': [u'Astronomy', u'Astronomy'], 'doctypeFacetHier': [u'0/Article [truncated]...
Diff is 4225 characters long. Set self.maxDiff to None to see it.

% python adsmsg/tests/test_fulltext_update.py 
Traceback (most recent call last):
  File "adsmsg/tests/test_fulltext_update.py", line 5, in <module>
    from adsmsg import FulltextUpdate
ImportError: cannot import name FulltextUpdate

**Comment by spacemansteve** [comment]
I believe previous simple changes to __init__.py did not use the pull request review cycle.  I will follow this pattern.
